version: "3"
services:
    frontend:
        stdin_open: true
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: margegaj24/web
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        depends_on:
          - mongodb
        image: margegaj24/server
        ports:
            - "4004:4004"
        volumes:
            - ./server:/usr/src/app
